### ISSUE TITLE
2557 video on must, logo näitab

### ISSUE THREAD

**Issue by mitselek** [argoroots/Screenwerk#6]

**Comment by mitselek** [comment]
Pole suutnud viga taasluua:
- osx yosemite 
  - node-webkit-v0.10.5-osx-ia32
  - ScreenWerk v.0.2.0-alpha.17
- windows xp
  - node-webkit-v0.10.4-win-ia32\nw.exe
  - ScreenWerk v.0.2.0-alpha.17

**Comment by miikael** [comment]
NW 0.10.5 ja SW 0.2-alpha.12.2 puhul mängib 2557 ühe tsükli. Script.js'ist vaadates versiooni näitab 0.2-alpha.10 ehk siis githubi jama olnud. Testisime sellega hetkel kuna see viimane versioon ilma relunchita, ehk uusim versioon mis töötaks hetkel linuxil.

**Comment by mitselek** [comment]
[alpha.22](https://github.com/argoroots/Screenwerk/releases/tag/0.2.0-alpha.22) viga ikka veel esineb?

**Comment by miikael** [comment]
Ei ole esinenud hetkel seda viga alpha.22 puhul
