### ISSUE TITLE
SW ei kuva veebilehtede (piletilevi.ee) pilte uuema node-webkitiga

### ISSUE THREAD

**Issue by miikael** [argoroots/Screenwerk#8]
Screenwerk ei kuva piletilevi leheküljel olevaid pilte.

Sama nii windowsil kui linuxil:
node-webkit-v0.11.5-win-x64
node-webkit-v0.11.5-win-ia32
node-webkit-v0.11.5-linux-64

Screenwerk-0.2.0-alpha.17

**Comment by mitselek** [comment]
kas urli vahetamine (http://www.piletilevi.ee/est/ -> http://www.piletilevi.ee/) muutis asja ka @miikael'i arvutis?

**Comment by miikael** [comment]
Kahjuks "est" järelt võtmine asja ei muutnud. Samuti kui tahta kuvada näiteks mõnda kategooriat "Teater", "Sport" jne, siis tuleb see "est" sinna vahele ka.

**Comment by mitselek** [comment]
alpha.24 kasutab node-webkit-v0.11.6
proovi igaks petteks sellega ka.

**Comment by miikael** [comment]
Playlist 2719 ja alpha.25 koos oma nw11.6'ga kuvab kodulehel pilte.
Müügivõrgu playlistid (nt 4094 jne) need alpha.25 koos nw11.6'ga pilte ei kuva.
Proovisin siis win64 ja linux64 peal ning mõlemaga 2719 kuvab piletilevi.ee lehti ja 4094 ei kuva.

**Comment by mitselek** [comment]
Väga hea! Nüüd me peame välja nuhkima, mis täpselt on see eriline asi, mis koduka pildid untsu ajab!

**Comment by mitselek** [comment]
Näib, et tegu on mingite uuema webkiti mahulimiitidega, mida ma ei suuda identifitseerida.
Lahendusene kasutame nüüd node-webkit versiooni 0.8.6.
